CREATE TABLE dodatki_extra (
  id_dodatku    NUMBER(2)
                GENERATED BY DEFAULT ON NULL AS IDENTITY
                CONSTRAINT dod_pk PRIMARY KEY,
  pseudo        VARCHAR2(15)
                CONSTRAINT dod_koc_pseudo_fk REFERENCES kocury(pseudo),
  dodatek_extra NUMBER(3)
                CONSTRAINT dod_dodatek_extra_nn NOT NULL
);

CREATE OR REPLACE TRIGGER check_extra
BEFORE UPDATE OF przydzial_myszy ON kocury
FOR EACH ROW
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  IF :NEW.funkcja = 'MILUSIA' AND :NEW.przydzial_myszy > :OLD.przydzial_myszy THEN
    IF LOGIN_USER != 'TYGRYS' THEN
      DBMS_OUTPUT.PUT('Zmian dokonal: ' || LOGIN_USER);
      EXECUTE IMMEDIATE 'DECLARE
                          CURSOR milusie IS SELECT pseudo
                                              FROM kocury
                                              WHERE funkcja = ''MILUSIA'';
                        BEGIN
                          FOR milusia IN milusie
                          LOOP
                            INSERT INTO dodatki_extra (pseudo, dodatek_extra)
                            VALUES (milusia.pseudo, -10);
                          END LOOP;
                        END;';

      COMMIT;
    END IF;
  END IF;
END;

UPDATE kocury
   SET przydzial_myszy = przydzial_myszy + 10
 WHERE funkcja = 'MILUSIA';

ROLLBACK;

DROP TRIGGER check_extra;

DROP TABLE dodatki_extra;
